### ISSUE TITLE
Partner Connect Failed - "Connect Merchant" API endpoint is called repeatedly every 10 minutes with same params

### ISSUE THREAD

**Issue by ivanrios** [woocommerce/pinterest-for-woocommerce#501] opened 2022-07-26 20:42 UTC
**API route**
/v3/catalogs/partner/connect/

**Error:**
Partner connect failed with exception Sorry! ghazalparis.com has already been claimed by another user.

<img width="999" alt="Screen Shot 2022-07-26 at 15 18 39" src="https://user-images.githubusercontent.com/1007705/181108078-191d1613-eae8-477a-96c3-2d6050cba991.png">

**Comment by adarshakb** [comment] 2022-07-26 22:01
Expected result: we shouldnt call the API repeatedly. We should show alert to user that website is already claimed and ask them to disconnect there. Then they can disconnect/reconnect woocommerce plugin

**Comment by alexiglesias31** [comment] 2022-08-17 16:35
@ivanrios  Could you please provide the steps to reproduce this issue? 

From my understanding of the picture, the error indicates that the domain is already claimed by another Pinterest business account.
The onboarding should be blocked on step 2 for such cases.
![image](https://user-images.githubusercontent.com/40774170/185192676-f66d4b4c-669b-4a19-8036-36263d4814c7.png)

Not sure if this issue can be related to #363 or it was caused by some error on the plugin update to v1.0.9 which introduced website verification instead of domain verification.

**Comment by budzanowski** [comment] 2022-11-10 11:10
Please investigate if the calls are made if the site is claimed by another user. If they are then this will require a solution. If not then we can close this.

**Comment by alexiglesias31** [comment] 2022-11-16 19:21
I couldn't reproduce the original issue, [this blocker](https://github.com/woocommerce/pinterest-for-woocommerce/issues/501#issuecomment-1218252720) was added to prevent such cases.
I couldn't see any calls, because the onboarding is blocked if the site is claimed by another user. In any case, I think it worth to double check this before closing the issue.

**Comment by message-dimke** [comment] 2023-04-06 17:05
I was not able to reproduce this. Closing it.

**Closed as completed by message-dimke** 2023-04-06 17:05 UTC
Labels: type: bug, priority: high
