### ISSUE TITLE
Disable the option "Enable Product Sync" and then enable it again is not working properly

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#346] opened 2022-02-01 14:30 UTC
### Describe the bug:
If MErchant desides to Disbale and then enable the option "Enable Product Sync" the feed is not been registered properly on Pinterest
![image](https://user-images.githubusercontent.com/43881685/151987278-65ce035d-c2a2-402f-8d1e-552742c00094.png)

```
2022-02-01T14:18:11+00:00 DEBUG POST Request: https://api.pinterest.com/v3/catalogs/partner/connect/

{"merchant_domains":"https:\/\/necked-barnacle.jurassic.ninja","feed_location":"https:\/\/necked-barnacle.jurassic.ninja\/wp-content\/uploads\/pinterest-for-woocommerce-5MWMsK.xml","feed_format":"XML","country":"US","locale":"en-US","currency":"USD","merchant_name":"Auto-created by Pinterest for WooCommerce"}

2022-02-01T14:18:12+00:00 DEBUG Response: 

HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 121
pinterest-version: d6f8a02
x-content-type-options: nosniff
x-frame-options: DENY
x-userendpoint-ratelimit-limit: 50000
x-userendpoint-ratelimit-remaining: 31780
x-envoy-upstream-service-time: 64
x-pinterest-direct: true
pinterest-generated-by: coreapp-ngapi-prod-0a010697
Cache-Control: no-cache, no-store, must-revalidate
x-pinterest-rid: 1150517336905927
Date: Tue, 01 Feb 2022 14:18:12 GMT
Connection: close
Set-Cookie: _ir=0; Max-Age=1800; HttpOnly; Path=/; Secure
AKAMAI-GRN: 0.9819df17.1643725092.4a92a23d
X-CDN: akamai

{"code":0,"data":"1503047420975","message":"ok","endpoint_name":"v3_create_commerce_partner_merchant","status":"success"}

2022-02-01T14:18:12+00:00 DEBUG GET Request: https://api.pinterest.com/v3/catalogs/1503047420975/feed_profiles/

--- EMPTY STRING ---

2022-02-01T14:18:12+00:00 DEBUG Response: 

HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 930
pinterest-version: d6f8a02
x-content-type-options: nosniff
x-frame-options: DENY
x-userendpoint-ratelimit-limit: 50000
x-userendpoint-ratelimit-remaining: 31777
x-envoy-upstream-service-time: 63
x-pinterest-direct: true
pinterest-generated-by: coreapp-ngapi-prod-0a010198
Cache-Control: no-cache, no-store, must-revalidate
x-pinterest-rid: 1301017846792919
Date: Tue, 01 Feb 2022 14:18:12 GMT
Connection: close
Set-Cookie: _ir=0; Max-Age=1800; HttpOnly; Path=/; Secure
AKAMAI-GRN: 0.9819df17.1643725092.4a92a2eb
X-CDN: akamai

{"code":0,"data":[{"host":null,"feed_default_currency":"USD","feed_status":"ACTIVE","location_config":{"update_feed_fetch_freq":0,"full_feed_fetch_location":"https://necked-barnacle.jurassic.ninja/wp-content/uploads/pinterest-for-woocommerce-sJeECE.xml","update_feed_fetch_location":"","full_feed_fetch_freq":0},"feed_username":null,"created_at":1643724838198,"domain":null,"preferred_schedule":null,"merchant_id":"1503047420975","country":"US","feed_has_password":false,"feed_format":"XML","integration_platform_type":"WOOCOMMERCE","updated_at":1643724838198,"id":"1577972926811","feed_index":0,"merchant_feed_id":"","display_name":null,"feed_type":"default","locale":"en-US","credential":{"short_term_token_type":null,"ltt_expiration_at":null,"stt_created_at":null,"ltt_created_at":null,"stt_expiration_at":null,"long_term_token_type":null}}],"message":"ok","endpoint_name":"v3_get_feed_profiles_by_merchant","status":"success"}

2022-02-01T14:18:12+00:00 ERROR No feed found with the requested location.
```

### Steps to reproduce:
1. Install pinterest plugin and do the onboarding with merchant
2. After feed is generated and registered on Pinterest, disable the option "Enable Product Sync"
3. Enable again the option "Enable Product Sync"

### Expected behavior:
feed is generated and registered again in Pinterest

### Actual behavior:
ERROR  No feed found with the requested location. is showing on logs and feed is not registered on Pinterest

**Comment by alexiglesias31** [comment] 2022-02-14 22:28
@jconroy, this issue was caused because the Pinterest API didn't allow to update the feed location using the endpoint `catalogs/partner/connect/` as described in the documentation. The API was updated and now this issue is not present any more.

**Comment by findingsimple** [comment] 2022-02-15 01:13
Thanks @alexiglesias31 

If @ChristianAF is able to check the issue is resolved for him we can close it out.

**Comment by alexiglesias31** [comment] 2022-02-17 14:40
The issue was verified as resolved by @ChristianAF. Proceding to close it out.

**Closed as completed by alexiglesias31** 2022-02-17 14:40 UTC
Labels: type: bug
