### ISSUE TITLE
Onboarding error when trying to claim a site when it's already claimed on Pinterest

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#476] opened 2022-06-10 14:52 UTC
“2022-06-08T15:10:15+00:00 ERROR Sorry! We couldn't find that merchant. Please ensure you have access and a valid merchant id.”

this happens on the Step 2 of the onboarding when merchants want to claim the site.

**Comment by findingsimple** [comment] 2022-06-16 03:07
Can we please try to include some of the issue template information to maintain high-quality issue/repo hygiene?

Describe the bug:
Steps to reproduce:
Expected behavior:
Actual behavior:
Additional details:

**Comment by alexiglesias31** [comment] 2022-06-21 19:32
@ChristianAF @jconroy, this is the actual behavior when a user tries to verify a domain that is already claimed by another user. A clear error is showed to the user. Are we expecting a different flow here?

![pinterest-domain](https://user-images.githubusercontent.com/40774170/174882579-6f2f4a27-ab88-4178-be03-d31453afe39c.png)

**Comment by ChristianAF** [comment] 2022-06-21 20:15
but the error is other “2022-06-08T15:10:15+00:00 ERROR Sorry! We couldn't find that merchant. Please ensure you have access and a valid merchant id.”

In this case the Merchant has already claimed the site on Pinterest.

@alexiglesias31

**Comment by findingsimple** [comment] 2022-07-04 11:56
@ChristianAF So are you saying the error reported “2022-06-08T15:10:15+00:00 ERROR Sorry! We couldn't find that merchant. Please ensure you have access and a valid merchant id.” doesn't match what is happening  "claim a site when it's already claimed on Pinterest" ?

I'm just going to note again - "Can we please try to include some of the issue template information to maintain high-quality issue/repo hygiene?: [ref](https://github.com/woocommerce/pinterest-for-woocommerce/issues/476#issuecomment-1157180755)  - I think it would be useful to clean up the original issue comment and be very clear about what the problem is.

**Comment by findingsimple** [comment] 2022-08-03 04:09
@alexiglesias31 @ChristianAF can you provide an update on this issue?

I can see in @alexiglesias31 [comment here](https://github.com/woocommerce/pinterest-for-woocommerce/issues/476#issuecomment-1162242136) that the error message is "We were unable to claim the domain...has already been claimed by another user" but @ChristianAF you are saying you are seeing "“2022-06-08T15:10:15+00:00 ERROR Sorry! We couldn't find that merchant. Please ensure you have access and a valid merchant id.”

Can we please clean up the initial PR description to clarify

**Comment by alexiglesias31** [comment] 2022-09-26 15:07
Closing this issue, since the customer didn't replied again. If the issue arises again at some point we can reopen it or create a new one with a more clear description.

**Closed as completed by alexiglesias31** 2022-09-26 15:07 UTC
Labels: type: bug, priority: high
