### ISSUE TITLE
Checkout completed event not working with Mollie checkout

### ISSUE THREAD

**Issue by linamarketing** [woocommerce/pinterest-for-woocommerce#408] opened 2022-03-22 10:38 UTC
Hi, on webshop https://kauwsieradenenmeer.nl we use Mollie payment provider in checkout and the only Pinterest event that is not registering is the most important one: Checkout conversion. In Pinterest it's reported as "Unknown" while other events are working correctly. There is also no value attributed to this event.

Mollie is one of the most popular payment gateways in The Netherlands.

How do we fix it? When someone clicks to pay they go to mollie.com/checkout/xxxx

Thanks.

Lina

**Comment by findingsimple** [comment] 2022-03-22 10:55
Hi @linamarketing 

I suspect the crux of the issue is related to "When someone clicks to pay they go to mollie.com/checkout/xxxx" - it sounds like the Woo thankyou page is not displaying in your flow

https://github.com/woocommerce/pinterest-for-woocommerce/blob/5184c88536304ca181da769560ff815387f4c562/src/Tracking.php#L99

Do merchants get redirected back to your site at all?

I'm going to mark as a compatibility issue for now.

**Comment by linamarketing** [comment] 2022-03-22 11:13
Thanks for the response, yes in Google Analytics goal urls I see there are hits on urls like this:

/afrekenen/order-received/XXXXX/?key=wc_order_xxxxxxxxxxx


so what could be the issue then?

**Comment by findingsimple** [comment] 2022-03-24 00:27
Hi @linamarketing are you able to confirm if you are using the default thankyou page template or if you are using a custom one?

I can see the site has a "focused-checkout" - is that added by a plugin or is it part of the theme you are using?

Basically, I'd like to confirm if your thank you page template has the equivalent of this line 

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/checkout/thankyou.php#L26

**Comment by linamarketing** [comment] 2022-03-28 09:07
Hi, this is what I see in the code:
<img width="1051" alt="Screenshot 2022-03-28 at 11 04 10" src="https://user-images.githubusercontent.com/42416236/160364807-b45ee419-8bf8-42d3-b01b-f9cadcf8b615.png">

The focused checkout seems to be part of the Flatsome theme we're using.

Cheers.

**Comment by findingsimple** [comment] 2022-03-28 10:43
Thanks @linamarketing - based purely on that snippet (if there is no other do_action above) it does appear like your theme is missing the standard `woocommerce_before_thankyou` hook  (but agan I can't be 100% certain as it is a small snippet.)

Essentially if it is missing ...

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/templates/checkout/thankyou.php#L26

... it won't be firing.

That is a core template hook so I think it's probably reasonable that your theme includes the same - otherwise, you could be missing more than just this conversion value.

For now I'm closing this. We may revisit the hook being used at some point but not in the next while.

**Closed as completed by findingsimple** 2022-03-28 10:43 UTC
Labels: category: compatibility

**Comment by linamarketing** [comment] 2022-03-28 11:04
No there is no other do_action. Ok thanks.
