### ISSUE TITLE
After accepting terms & creation of Advertiser it shows and error, the error goes on a infinit loop

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#162] opened 2021-08-17 13:40 UTC
### Describe the bug:
When accepting terms & creation of Advertiser with a new merchant it shows and error that goes to infinit loop, seems that the code if because "Argentina" is not yet available.

### Steps to reproduce:
1. Install plugin and do the onboarding 
2. Accept the terms & creation of Advertiser with a merchant of a country not availabe

#### Expected behavior
show the error one time, and not go to a infinit loop

#### Actual behavior
show the error and goes on a infinit loop

![loop error](https://user-images.githubusercontent.com/43881685/129736163-e12845d4-ccd6-4877-9d80-b1faf0502d0a.png)

**Comment by ecgan** [comment] 2021-09-28 19:24
@msaggiorato , I see that you are the assignee for this issue. FYI, I'm going to help look into this issue and I have just self-assigned this. Just wondering and want to make sure whether you are actively investigating and working on this?

**Comment by msaggiorato** [comment] 2021-09-28 19:27
Hey @ecgan , just removed myself, since i'm not actively working on this.

**Comment by ecgan** [comment] 2021-09-30 19:15
To reproduce this issue, I created a new Pinterest account (so that the plugin can create a new advertiser ID in it; the account has Argentina country region in https://www.pinterest.com/settings/account-settings), spin up a new site with a new domain (existing domains that have been claimed by other Pinterest accounts cannot be claimed again), and go through the onboarding.

Note that the Argentina country settings is referring to the one in Pinterest account settings; this issue is not affected by the store address in WooCommerce settings, you can have the WC store country set to US.

I don't see the infinite loop issue happening. In step 3, after checking the checkbox to accept agreement and clicking on the Continue button, there is an API call `GET /wp-json/pinterest/v1/tagowners/?terms_agreed=8&_locale=user`. When it failed, the UI shows an error message like the following, there is no infinite loop.

![image](https://user-images.githubusercontent.com/417342/135511171-4c9b34fa-7e23-4557-92c4-05ada997393e.png)

I believe the infinite loop issue has been fixed in PR https://github.com/woocommerce/pinterest-for-woocommerce/pull/200. 

However, the error message can be better improved though. The failed API response contains an error message like this: `"message: "Could not fetch advertisers for Pinterest account ID. [Error Processing Request: The country '36' is not yet available.]"`. 

@wjia88 @niketpins , the number "36" comes from Pinterest API side. Is it possible to make the Pinterest API error message more meaningful with country name so that we can display it and inform the user?

**Comment by ghost** [comment] 2021-09-30 23:39
Created tkt on our end to improve error messaging

**Comment by findingsimple** [comment] 2021-10-05 05:43
Thanks @ecgan, closing as the infinite loop is addressed

**Closed by findingsimple** 2021-10-05 05:43 UTC
Labels: type: bug, priority: high
