### ISSUE TITLE
Show a warning if a merchant's website is behind password and unreachable

### ISSUE THREAD

**Issue by JohnnyCYu** [woocommerce/pinterest-for-woocommerce#492] opened 2022-07-07 03:28 UTC
### Is your feature request related to a problem? 
Currently there is no warning if a merchant's website is behind password and unreachable, as part of the merchant verification process

### Describe the solution you'd like 
We should show a warning if a merchant's website is behind password and unreachable. 

## Technical
Please discuss with Adarsha from PINS team for more details

**Comment by findingsimple** [comment] 2022-08-03 04:24
From a design perspective we'll likely just take a similar approach to https://github.com/woocommerce/pinterest-for-woocommerce/issues/417

But we'll need to align on wording

@adarshakb can PINS take the first pass at wording here?

> We should show a warning if a merchant's website is behind password and unreachable.

@adarshakb do we get an API response from any requests indicating the site isn't reachable by Pinterest? I think it will be more fool proof and easier to maintain if we are telling users the site is not accessble from Pinterest rather than (as an example) looking for certain extensions such as maintenance mode plugins etc. 

@adarshakb can you edit the PR description with additional information - such as that above when you get a moment?

**Comment by ivanrios** [comment] 2022-08-10 23:31
This is the error we receive when website validation fails, either because the site is unreachable or behind an authorization restriction.

_[Status - Message]_
**503 -  7 seconds: /v3/websites/verification/metatag/realtime/ didn't finish after 7 seconds**


--------------

These are the additional possible errors trough the website validation.

Validation:

- 403 - Your website is in the process of being claimed and should be verified shortly.
- 403 - Domain failed to be verified. Try again!
- 403 - You're over your limit for website verifications. Try again later.
- 403 - Sorry! _{website}_ has already been claimed by another user.

Errors:

- 500 - A connection error occurred.
- 500 - An unexpected error occurred.
- 500 - No relevant meta tag was found.
- 500 - The meta tag had the wrong verification code.
- 500 - The request timed out.
- 500 - An HTTP error occurred.

**Comment by findingsimple** [comment] 2022-08-11 00:33
Thanks @ivanrios ! 🤔

**Comment by alexiglesias31** [comment] 2023-02-08 16:35
Hey @JohnnyCYu @adarshakb @ivanrios, do you have the steps to reproduce this?
I tried doing the following:
- Create a test site.
- Protect the site with http password.
- Install the plugin and do the onboarding.
- I get this error in the domain verification step.

![image](https://user-images.githubusercontent.com/40774170/217592522-3cd18227-d220-462f-a4c2-e136aea9dda1.png)

The error is returned by the API with the code 75. Since this issue has been here for a while I just want to be sure what are we fixing here. Thanks.

**Comment by message-dimke** [comment] 2023-03-01 22:09
I added Basic HTTP Auth and got `403 - Your website is in the process of being claimed and should be verified shortly.` Not sure what to fix here, if it is possible to get another message from Pinterest then the extension itself would just display it and that is it, nothing to fix.

**Comment by message-dimke** [comment] 2023-03-02 18:53
Hey, @alexiglesias31 ! Talked to @ivanrios , and we don't have a specific message for this (when a website is under auth), so  we can close this ticket.

**Closed as completed** 2023-03-20 19:09 UTC
Labels: type: enhancement, needs design
