### ISSUE TITLE
Pinterest plugin breaking a feature of "Side cart woocommerce" plugin

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#709] opened 2023-03-16 13:56 UTC
The side cart plugin does not auto-open after activating the Pinterest plugin.

https://wordpress.org/support/topic/compatible-32/

### Expected behavior:
The side cart should open automatically even if the Pinterest plugin is activated

### Actual behavior:
The side cart does not open automatically when the Pinterest plugin is activated

**Comment by ChristianAF** [comment] 2023-03-21 14:31
WordPress Environment

WC Version: 7.5.0
REST API Version: ✔ 7.5.0
WC Blocks Version: ✔ 9.6.5
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

Server Environment

Server Info: LiteSpeed
PHP Version: 8.1.4
PHP Post Max Size: 2 GB
PHP Time Limit: 1500
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 10.4.26-MariaDB
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

**Comment by message-dimke** [comment] 2023-04-12 07:02
Wasn't able to reproduce the issue using the plugins mentioned in the ticket. Wrote customer to provide some more information in the issue. For me Side Cart + Pinterest worked just fine.

![Beanie_with_Logo_–_WordPress_Pinterest](https://user-images.githubusercontent.com/9010963/231377776-ddda24ae-1601-4672-ac29-29a28c1f6658.png)

**Comment by message-dimke** [comment] 2023-06-08 19:39
Since I could not reproduce it and there is still no answer from the user at forums ( waiting for 1 month and 3 weeks already ) I am closing this ticket as the one we could not reproduce.

**Closed as completed by message-dimke** 2023-06-08 19:39 UTC
Labels: type: bug, category: compatibility
