### ISSUE TITLE
Remote sync status failed after the onboarding 

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#155] opened 2021-08-13 19:53 UTC
### Describe the bug:
The catalog sync is not working, an error is showing:
![image](https://user-images.githubusercontent.com/43881685/129411352-7a846d82-961e-4e38-862d-421d54aebc9b.png)

On the Pinterest Account:
![image](https://user-images.githubusercontent.com/43881685/129411605-f2c40df0-84ea-43ff-93b4-5182ebc7b86d.png)

### Steps to reproduce:
After the onboarding the catalog sync should be triggered after 10 minutes

**Comment by ksere** [comment] 2021-10-19 18:15
The original issue doesn't offer specific info to reproduce. Also since it was opened a lot of things have changed in the relevant parts of the plugin. 

The issue described by Rua [here](https://github.com/woocommerce/pinterest-for-woocommerce/issues/155#issuecomment-899117616) regarding `Invalid parameters` as far as I can tell is related to trying to update a feed profile with the wrong/leftover data from a previously saved merchant and should be fixed by the data cleanup on Auth disconnect. 

This is how the whole onboarding flow looks right now (this is with PR #227 included) :

https://user-images.githubusercontent.com/4016167/137967451-4d7d930e-2a8c-4c28-b4b6-80a02d559f81.mp4

@jconroy please verify if we can close this.

**Comment by findingsimple** [comment] 2021-10-27 23:44
Happy to close based on your findings @ksere

**Closed as completed by findingsimple** 2021-10-27 23:44 UTC
Labels: type: bug, priority: high
