### ISSUE TITLE
[p2] User cannot be connected to multiple active accounts

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#364] opened 2022-02-10 17:56 UTC
### Describe the bug:
A user cannot both register and shopify and Woocommerce. The API will fail. Since connecting the partner to feed and related functions happen after user registration process, there is an error. However that error is not displayed correctly to the user
### Steps to reproduce:

1. Create a new pinterest business account or have an account with no stores connected
2. first goto shopify and create a store and install pinterest app from app store
3. connect the business account to pinterest app in shopify
4. create a shop in woocommerce and install the pinterest plugin. 
5. connect the business account to woo commerce

### Expected behavior:
A clear error message is shown to user either during registration or in the setup screen when the error happens during feed process

### Actual behavior:
No error message shown

### Additional details:
![Screen Shot 2022-02-10 at 9 56 40 AM](https://user-images.githubusercontent.com/1510328/153467699-c756e22c-af53-4a84-8f51-a23435f7ad12.png)

**Comment by findingsimple** [comment] 2022-02-10 23:13
cc @shivanarrthine in case there is some specific design treatment you think would be preferable

**Comment by shivanarrthine** [comment] 2022-02-15 06:31
Using the notice banner is a good way to go, I don't think any specific design is necessary. The priority would be ensuring the messaging is clear with some next steps the merchant can take to resolve the issue.

**Comment by findingsimple** [comment] 2022-02-15 06:33
Thanks!

I'll add to the meeting agenda for tomorrow if anyone has ideas for the error message to be displayed

The is possible a good item to have in documentation

**Comment by findingsimple** [comment] 2022-02-22 22:53
Error message/text provided as part of the response

**Comment by adarshakb** [comment] 2022-02-22 23:07
On pinterest side here are the error details being send




Merchant has already connected to other platform
Partner connect failed with exception Merchant has already connected to other platform

**Comment by findingsimple** [comment] 2022-03-03 23:51
From slack - 

When trying to reproduce the issue the response from Pinterest looks like

`{"status":"failure","code":12,"data":{"request_id":"6551546475096428"},"message":"Something went wrong on our end. Sorry about that.","endpoint_name":"v3_create_commerce_partner_merchant"}`

@adarshakb is investigating why it is filtered at the API level on the pinterest site.

Marking as on hold until we here back

**Comment by adarshakb** [comment] 2022-03-07 17:05
I am updating the endpoint on pinterest side. I will keep you posted when the API gets updated.

**Comment by adarshakb** [comment] 2022-03-15 23:14
API should have a new error code.

Suggested text copy to display

Heading: Unable to upload catalog
Subheading: It looks like your Pinterest business account is connected to another e-commerce platform. Only one platform can be linked to a business account. To upload your catalog, disconnect your business account from the other platform and try again.

**Closed as completed** 2022-04-07 16:56 UTC
Labels: type: bug, priority: low
