### ISSUE TITLE
"Sorry, you are not allowed to access this page." on installation/activation - possibly due to WC core 9.1.2?

### ISSUE THREAD

**Issue by sophiegyo** [woocommerce/pinterest-for-woocommerce#1040] opened 2024-07-23 13:47 UTC
### Describe the bug:
When installing these versions of Pinterest for WooCommerce, you just get a "Sorry, you are not allowed to access this page." message after activating the extension. 

I have tried and replicated this, several times. 

### Steps to reproduce:
1. Use playground.wordpress.net for a quick setup
2. Install current version of WooCommerce (9.1.2) and activate it
3. Install current version of Pinterest for WooCommerce (1.3.24) and activate it

I have tested this with:

WooCommerce core 9.1.2 + Pinterest for WooCommerce 1.3.24 = reproduced
WooCommerce core 9.1.2 + Pinterest for WooCommerce 1.4.0 = reproduced
WooCommerce core 9.1.2 + Pinterest for WooCommerce 1.4.1 = reproduced
WooCommerce core 9.1.2 + Pinterest for WooCommerce 1.4.2 = reproduced
WooCommerce core 9.1.2 + Pinterest for WooCommerce 1.4.4 = RESOLVED
WooCommerce core 9.1.2 + Pinterest for WooCommerce 1.4.5 = RESOLVED

WooCommerce core 9.1.1 + Pinterest for WooCommerce 1.3.24 = reproduced
WooCommerce core 9.1.0 + Pinterest for WooCommerce 1.3.24 = reproduced

Side note: I double-checked release version 1.4.3 of Pinterest for WooCommerce, but the zip there is definitely 1.4.2 instead, I tested it twice to be sure. So, I don't know whether that version technically has the issue or not.

### Expected behavior:
The error message should not show up.

### Actual behavior:
The error message shows up as soon as Pinterest for WooCommerce is activated. It's not possible to proceed with the setup.

Here's my recording:

https://github.com/user-attachments/assets/a87a1eed-1997-41a1-8268-0bcf693744cb

### Additional details:
I'm not sure when this might have kicked in, but we're seeing a few forum threads about it now. 
Also reported in 8507842-zen

**Comment by layoutd** [comment] 2024-07-23 14:12
Thanks @sophiegyo, I can also reproduce it and will look at determining the root cause and getting a fix out ASAP.

**Comment by wyter** [comment] 2024-07-23 14:13
Also reported on the forums:
* https://wordpress.org/support/topic/marketing-pinterest-sorry-you-are-not-allowed-to-access-this-page/
* https://wordpress.org/support/topic/can-someone-please-help-me-sorry-you-are-not-allowed-to-access-this-page/

**Comment by layoutd** [comment] 2024-07-23 14:53
This appears to be related to this issue: https://github.com/woocommerce/pinterest-for-woocommerce/issues/1031
A fix was merged and released in the GH-only releases (1.4.x) but wasn't added to the .ORG releases (1.3.x).

**Comment by layoutd** [comment] 2024-07-23 17:55
@sophiegyo @wyter Thanks again for surfacing this, the issue should be resolved with the just-released version 1.3.25.

**Closed as completed by layoutd** 2024-07-23 17:55 UTC
Labels: type: bug
