### ISSUE TITLE
Partner Connect Failed - Investigate Duplicated calls to Connect merchant API 

### ISSUE THREAD

**Issue by ivanrios** [woocommerce/pinterest-for-woocommerce#500] opened 2022-07-26 20:12 UTC
Error message: 
  Partner connect failed with exception " Merchant has already connected to other platform"

<img width="948" alt="Screen Shot 2022-07-25 at 18 27 58" src="https://user-images.githubusercontent.com/1007705/181102289-683d8010-abef-4ba9-94f8-fa56067601a7.png">

 This error was generated 75k times in the last 2 weeks

**Comment by adarshakb** [comment] 2022-07-26 22:02
Expected result: we shouldnt call the API repeatedly. We should show alert to user that website is already claimed and ask them to disconnect there. Then they can disconnect/reconnect woocommerce plugin

**Comment by findingsimple** [comment] 2022-08-03 03:56
Noting that possibly similar/related solution needed for https://github.com/woocommerce/pinterest-for-woocommerce/issues/501

**Comment by alexiglesias31** [comment] 2022-08-17 17:04
There is an error displayed to the user on that case.
![image](https://user-images.githubusercontent.com/40774170/185199129-d5516293-4307-4275-82de-6fea15e32190.png)

The call to the `partner/connect/` endpoint happens when the plugin tries to register the feed, which should happen every 10min.
@ivanrios could you please provide some steps to reproduce this issue, to be sure that nothing is missed there.

There is an ongoing [PR](https://github.com/woocommerce/pinterest-for-woocommerce/pull/512) to add a back off mechanism to those cases.

**Comment by adarshakb** [comment] 2023-01-05 17:50
>There is an ongoing https://github.com/woocommerce/pinterest-for-woocommerce/pull/512 to add a back off mechanism to those cases.

This should be good. We dont want to spam Pinterest servers

**Comment by message-dimke** [comment] 2023-04-06 16:56
Closing this because of https://github.com/woocommerce/pinterest-for-woocommerce/pull/610

**Closed as completed by message-dimke** 2023-04-06 16:56 UTC
Labels: type: bug, priority: high
