### ISSUE TITLE
Pinterest plugin blocking Printful plugin to connect

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#713] opened 2023-03-27 16:03 UTC
### Describe the bug:

> I have been suffering from a synchronization problem between my site and Printful for two months, and Printful support and hosting support have also suffered to solve this problem, but unfortunately, they could not solve it until I hired a specialist and unfortunately it was found that the problem was in the “Pinterest for WooCommerce plugin” It’s blocking Printful from accessing my site.

Note: still waiting for the System Report from the user.

https://wordpress.org/support/topic/it-caused-problems-in-my-site/

**Comment by ghost** [comment] 2023-03-31 00:20
please,
I sent the System Report in response to the email sent to me, and there is no response yet.

**Comment by message-dimke** [comment] 2023-06-07 20:39
Hey, @rafatbarakat ! 


Do you still have any issues with Pinterest, because I was not able to reproduce the issue. I have both plugins work for me w/o any issues. 

<img width="1366" alt="Dashboard_‹_WordPress_Pinterest_—_WordPress" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/861de4bd-4019-4073-90e9-a928f5cc814a">

Here is the list of plugins I have 

<img width="1366" alt="Plugins_‹_WordPress_Pinterest_—_WordPress" src="https://github.com/woocommerce/pinterest-for-woocommerce/assets/9010963/c437e80e-707d-4b44-8f0e-e4cb65d8d8c0">

Not sure the problem is with Pinterest extension.

**Comment by ghost** [comment] 2023-06-07 21:19
The problem resolved itself after updating the Pinterest plugin

Thank you

‫في الأربعاء، 7 يونيو 2023 في 11:39 م تمت كتابة ما يلي بواسطة ‪Dmytro‬‏ <‪
***@***.***‬‏>:‬

**Comment by message-dimke** [comment] 2023-06-08 19:36
Thank you, @rafatbarakat ! I am closing the issue as the one which is not relevant anymore.

**Closed as completed by message-dimke** 2023-06-08 19:36 UTC
Labels: type: bug, priority: low, needs feedback, category: compatibility
