### ISSUE TITLE
Investigate why the following websites have Missing conversion value in checkout

### ISSUE THREAD

**Issue by adarshakb** [woocommerce/pinterest-for-woocommerce#410] opened 2022-03-22 22:31 UTC
(@jconroy has updated the list below with additional findings/information about each store)

- https://www.kpop-culture.fr/
  - (stripe or paypal + regular checkout)
  - I think they removed the extension - I don't see our code in the source - but events are still firing
  - Google Tag Manager
- https://raydasher.com/
  - (cartimize checkout - looks like it has a custom thank you page) - 1.0.1
  - bunch of pintrk events on every page not added by us
  - can't see pinit.js
  - stray `pintrk('track', 'checkout');` in source with no values on every page view
- https://store.cloverleafdistribution.com
  - (ww.checkoutwc.com checkout - custom thank you) - 1.0.3
  - Google Tag Manager
  - don't think they are using the extension anymore - can't see API routes 
- https://themeparkcandles.com/
  - Jason - FYI SSL cert is broken  on this site)
- https://allwoolthatendswool.co.uk
  - (Paypal - regular checkout)
  - Google Tag Manager
  - Fires a checkout event on every page load but I can't see out code added in source - suspect it might be something stray in Google tag manaager

**Comment by adarshakb** [comment] 2022-03-22 22:34
Please check all the websites linked individually. Some of them may no longer exhibit the behaviour if there is a change in their setup as data is couple of day old

**Comment by findingsimple** [comment] 2022-03-22 22:35
Thanks @adarshakb

Making a note - discussed on call that its possible fixing other tagging/event issues may resolve this - but its been difficult to replicate by the pinterest team.

**Comment by findingsimple** [comment] 2022-03-23 12:10
Documenting a thought which may be picked up in a separate issue.

The extension hooks into `woocommerce_before_thankyou` which [can be fired on failed orders](https://stackoverflow.com/questions/61821083/does-the-woocommerce-thankyou-action-hook-fire-on-failed-orders) and it doesn't look like it takes into account the status - if this holds it might be the cause of at least some checkout events looking weird

Update - I checked viewing the thank you page with a failed order on my a test site and the checkout event didn't have any issues (however it was an order I had which I simply changed the status of)

**Comment by adarshakb** [comment] 2022-03-25 03:02
> have a if() check somewhere to check that order passed

**Comment by findingsimple** [comment] 2022-03-25 04:30
> have a if() check somewhere to check that order passed

We only check for an order object 

https://github.com/woocommerce/pinterest-for-woocommerce/blob/develop/src/Tracking.php#L248-L250

I tried today to try and replicate a failed order during checkout but "failed" at that.

@budzanowski or @JPry do you think we need add an additional status check before adding the checkout event code?

**Comment by findingsimple** [comment] 2022-03-31 03:23
A number of the example sites above should be address with https://github.com/woocommerce/pinterest-for-woocommerce/issues/417

**Comment by findingsimple** [comment] 2022-07-07 01:46
I think the remaining element of this issue is investigating [if we need additional checks for failed orders](https://github.com/woocommerce/pinterest-for-woocommerce/issues/410#issuecomment-1078644333).

**Comment by alexiglesias31** [comment] 2022-11-07 16:30
Hey @jconroy @adarshakb, an update on this issue.

- https://www.kpop-culture.fr/
   - The plugins seems to be active, since the `p:domain_verify` is present on the head and the API routes are registered.
   - `pinit.js` is also being loaded.
   - Perhaps they disabled the tracking events, since I couldn't see any of the events firing.
- https://raydasher.com/
   - I think they removed the plugin, since the API routes are not registered and the domain verify tag is not present.
   - I couldn't see any reference to `pintrk`
- https://store.cloverleafdistribution.com/
   - I think they removed the plugin, since the API routes are not registered and the domain verify tag is not present.
   - I couldn't see any reference to `pintrk`
- https://themeparkcandles.com/
   - The tag related code it's different to the plugin, perhaps they are using a different extension for Tracking or a custom implementation.
      - The comments around the Pinterest Tag in <head> is `Pinterest Tag` , the plugin uses `Pinterest Pixel Base Code`.
      - There are 2 add to cart events on every page load which is exactly the same of [the example in the help section](https://help.pinterest.com/en/business/article/add-event-codes#section-16176).
- https://allwoolthatendswool.co.uk
   - Everything seems to be working fine, the events load, pagevisit and addtocart are working properly.
   - I didn't complete a checkout process, but I couldn't reproduce the checkout event firing on every page load.

**Comment by alexiglesias31** [comment] 2023-01-26 22:48
@budzanowski @message-dimke, please let me know if we can close this issue :slightly_smiling_face:

**Comment by alexiglesias31** [comment] 2023-01-30 14:34
Closing this after getting confirmation via Slack.

**Closed as completed by alexiglesias31** 2023-01-30 14:34 UTC
Labels: type: bug, priority: low
