### ISSUE TITLE
Compatibility w/Elementor Pro

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/pinterest-for-woocommerce#860] opened 2023-11-28 06:37 UTC
### Describe the bug:
If Pinterest and Elementor Pro are installed on the same site, cart functions cease to work as expected

### Steps to reproduce:

1. Pinterest installed/active
2. Elementor Pro installed/active
3. Add a product to the cart. 
4. On the cart page, attempt to add a coupon.

### Expected behavior:
That the coupon is added and the cart totals refresh with an updated total, or, if the coupon is invalid, a message indicating that.

### Actual behavior:
a JavaScript error happens and the coupon isn't applied.

### Additional details:

![Nzp5l3.png](https://github.com/woocommerce/pinterest-for-woocommerce/assets/2127470/50de2ecc-51a7-434f-be90-b7b571b352ee)
![E6enCz.png](https://github.com/woocommerce/pinterest-for-woocommerce/assets/2127470/48b2bd21-cf84-4a9f-b3f6-719c024613ee)

**Comment by WillBrubaker** [comment] 2023-11-30 03:43
FWIW, this doesn't happen with the cart block.

**Comment by ibndawood** [comment] 2023-12-01 15:25
Thank you, @WillBrubaker, for reporting this issue. We'll investigate the issue and update you.

**Comment by ecgan** [comment] 2023-12-04 17:01
Adding a dev note: the error message (`t.addClass(...).block is not a function`) in the screenshot is thrown from this line:

https://github.com/woocommerce/woocommerce/blob/4b63874ff8646507a56d7e94f8bacf5b010be34a/plugins/woocommerce/client/legacy/js/frontend/cart.js#L41

**Comment by ecgan** [comment] 2023-12-04 17:40
Hi @WillBrubaker , I checked the reported ticket (7358576-zd-a8c) and also the affected website mentioned in the ticket. It seems like the issue has been resolved by the user and it is not caused by our Pinterest plugin here. Could you confirm this please?

**Comment by WillBrubaker** [comment] 2023-12-05 06:05
@ecgan My understanding is they were able to resolve it by making adjustments to another plugin's settings.

**Comment by ecgan** [comment] 2023-12-05 10:08
Closing this issue since it has been resolved by the user, by making adjustments to another plugin's settings.

**Closed as completed by ecgan** 2023-12-05 10:08 UTC
Labels: type: bug, category: compatibility
