### ISSUE TITLE
Subscription products that are "Out of stock" are included on feed when the hide out of stock products option is not checked on WooCommerce

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#508] opened 2022-08-08 15:37 UTC
### Describe the bug:
If the option "Out of stock visibility" is not checked, and there are Subscription products out of stock, they will appear on the feed.
Woo option on "/wp-admin/admin.php?page=wc-settings&tab=products&section=inventory"
<img width="603" alt="image" src="https://user-images.githubusercontent.com/43881685/183456156-89b294ef-5848-42d0-9445-be4ef3119704.png">

Feed: 
[pinterest-for-woocommerce-5yx2F3.xml.zip](https://github.com/woocommerce/pinterest-for-woocommerce/files/9283092/pinterest-for-woocommerce-5yx2F3.xml.zip)

### Steps to reproduce:

1. uncheck the option "Out of stock visibility" on "/wp-admin/admin.php?page=wc-settings&tab=products&section=inventory"
2. Subscription products that are out of stock should be present on the site.
3. Install Pinterest 1.2.1 version
4. Do the onboarding and wait until the Feed is created or do it manually on the Scheduled actions.

### Expected behavior:
Subscription products should be hidden no matter if the  "Out of stock visibility" 

### Actual behavior:
Subscription products are not excluded if  "Out of stock visibility" is unchecked

**Comment by budzanowski** [comment] 2022-12-22 18:57
Although we will add a filter that disables the Subscription products we should still investigate why a such product is included.

**Comment by alexiglesias31** [comment] 2023-01-25 11:10
After some digging I was able to reproduce the error with the plugin versions < 1.2.9 and the same set of products that @ChristianAF used to report the issue. I found there is some kind of corruption in the DB, there are 4 products listed as product variations and the parent set to a subscription which is not variable. The 4 corrupted product are read as simple `variation`.

![image](https://user-images.githubusercontent.com/40774170/214543697-51c87173-f3a5-45f2-adfe-0034efafe52b.png)

A possible workaround would be to tweak the `get_excluded_products_by_parent` to exclude all the product where the parent is not a variable product, as a more strict condition, but that may be a bit over-engineered.

Please @budzanowski @message-dimke let me know what do you think and if we move forward with the tweak or simply discard the issue.

**Comment by alexiglesias31** [comment] 2023-01-30 14:36
Closing this, since this is no longer applicable after PR #496.

**Closed as completed by alexiglesias31** 2023-01-30 14:36 UTC
Labels: type: bug, needs feedback
