### ISSUE TITLE
Verified domain section is not claimed, when Url has a capitalized letter

### ISSUE THREAD

**Issue by ChristianAF** [woocommerce/pinterest-for-woocommerce#454] opened 2022-04-28 14:02 UTC
### Describe the bug:
if the url has a Capitalized letter like https://url.com/**S**hop on the settings page looks like the site is not clamied.

![image](https://user-images.githubusercontent.com/43881685/165769675-f0175373-b14d-4114-9b86-1d573900c278.png)

### Steps to reproduce:

1. Install and do the onboarding with a site that has on the URL a capitalized letter
2. once finished go to settings

### Expected behavior:
Site should still be claimed

### Actual behavior:
Site looks like is not claimed

**Comment by findingsimple** [comment] 2022-05-03 02:01
@adarshakb does the Pinterest API accept capitalization?

**Comment by adarshakb** [comment] 2022-05-04 22:21
From initial investigation, it looks like our endpoint makes the path all lowercase. I have asked internal team to investigate. Will get back with more details

**Comment by adarshakb** [comment] 2022-05-05 22:29
Internal team has a fix ready and is testing it. Thanks for flagging it.

**Comment by findingsimple** [comment] 2022-05-06 01:16
Thanks @adarshakb - I'll leave this open until we confirm working. Let us know and then perhaps @alexiglesias31 can give it a test and close

**Comment by adarshakb** [comment] 2022-05-10 21:53
This has been fixed on pinterest now.

**Comment by alexiglesias31** [comment] 2022-05-13 20:42
I can confirm that this is working.

![image](https://user-images.githubusercontent.com/40774170/168386777-43b45eca-ec15-4ac8-a377-73f2d8a5289d.png)

Closing the issue.
cc @jconroy @adarshakb @ChristianAF

**Closed as completed by alexiglesias31** 2022-05-13 20:42 UTC
Labels: type: bug, priority: low
